version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - env/mysql.env
    ports:
      - "3309:3306"
    restart: unless-stopped
    networks:
      - moto_manager_network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  moto_manager_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moto_manager_app
    depends_on:
      mysql_db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - moto_manager_network
    env_file:
      - env/application-properties.env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Porta padrão para o RabbitMQ
      - "15672:15672"   # Porta para o painel de administração
    networks:
      - moto_manager_network
    env_file:
      - env/rabbitmq.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  mysql_data:
  rabbitmq_data:

networks:
  moto_manager_network:
    driver: bridge
